### ISSUE TITLE
Brainstorm templates and layouts for inspiration

### ISSUE THREAD

**Issue by mapra99** [PradaIng/structuraid-desktop#56]

**Comment by mapra99** [comment]
@juanse1904 @mapra99 @ImMPrada to throw some ideas in here like the ones we talked about

I think the idea of making a Revit-like look is very strategic

**Comment by ImMPrada** [comment]
![Image](https://user-images.githubusercontent.com/26731448/233767953-cfdcb2fa-b943-46a0-bc2d-718b4c77e8c3.png)

**Comment by ImMPrada** [comment]
![Image](https://user-images.githubusercontent.com/26731448/233767908-80e9ad92-ccb2-4c83-a62a-94a8f0de2bd8.png)

**Comment by mapra99** [comment]
See some advances in the design here
https://design.penpot.app/#/workspace/d558d697-a49c-80fa-8001-ddb4d5a033f3/d558d697-a49c-80fa-8001-ddb730cb4a88?page-id=332e7a10-0073-80cb-8002-68c80b77781e
